"""Unique treatise copy for the Wump Institute volumes."""

BOOKS = []


def book(**kwargs):
    BOOKS.append(kwargs)
    return kwargs


book(
    slug="the-wump-life",
    title="THE WUMP LIFE",
    running="THE WUMP LIFE",
    subtitle="Wumping, Wumping to Live, and the<br/>Mathematics of the Great Wump",
    volume="Volume I of the Wump To Live Library",
    accent="#8a6a32",
    disclaimer=[
        "This book treats wumping with the seriousness reserved for migration, thermodynamics, and maritime law. The central proposition is useful: people need periodic experiences of effort, novelty, release, connection, and return. Here we call the combined phenomenon the wump.",
        "The shark is used as a figure of motion: stagnation feels dangerous, movement restorative. The field equations that follow are operational models for interval, intensity, and recovery, written so a life can be maintained.",
    ],
    preface_epigraph="A life without wumping is merely time passing.",
    preface_attr="First Principle of the Institute",
    preface=[
        "A wump is not merely an event. It is a unit of lived intensity: the moment when ordinary existence compresses, rebounds, and announces itself with unmistakable force. One may wump physically, socially, spiritually, rhythmically, or in the quiet privacy of one’s own internal wump chamber.",
        "This volume is the field guide. The later books will take you into the soul, the laboratory, and the archive. Here we stay with the practice itself: how a wump begins, how it completes, and how a person keeps from forgetting the sensation of being inhabited.",
        "The mature wumper stops asking, ‘How do I maximize wump?’ and asks, ‘What rhythm of intensity and recovery makes my life feel occupied from the inside?’ This is the difference between collecting peaks and developing a pulse.",
        "If you have arrived expecting a personality, we must disappoint you. If you have arrived expecting a pulse, you are in the right interval.",
    ],
    chapters=[
        {
            "title": "The Wump Instinct",
            "epigraph": "Stagnation feels dangerous. Movement, restorative.",
            "body": [
                "Some sharks must keep water moving across their gills. The wumper takes the lesson without confusion: stillness that lasts too long begins to feel like disappearance. Motion, even small motion, returns a person to themselves.",
                "Wumping begins with pressure. Something accumulates: boredom, energy, anticipation, curiosity, or the faint suspicion that Tuesday has become too Tuesday. The novice treats this pressure as a defect. The practitioner treats it as a fuse.",
                "Small wumps matter. A walk taken for no reason, a joke pursued far beyond reasonable limits, a meal cooked with theatrical seriousness, a project suddenly begun at 11:47 p.m. — these are micro-wumps. They keep the system elastic between major events.",
                "You do not need a festival. You need a complete cycle: compression, release, recovery. A life that skips any of the three will eventually feel like a story with the middle torn out.",
            ],
            "maxim": "The next wump should answer the last one, not imitate it.",
            "exercise": "Identify one thing in your current week that is merely happening and one thing that could be deliberately wumped. Increase the second by exactly 7% in spirit, not necessarily in measurable units.",
        },
        {
            "title": "Anatomy of a Proper Wump",
            "epigraph": "The novice thinks the wump is noise. The experienced wumper knows it is contrast.",
            "body": [
                "A proper wump has three movements, whether anyone writes them down or not. First, compression: the gathering. Second, release: the announcement. Third, recovery: the interval in which the announcement becomes memory instead of debris.",
                "People skip the first movement by detonating too early. They skip the third by stacking events until the nervous system can no longer tell one peak from the next. Both errors produce the same hangover: the feeling of having been busy without having been there.",
                "Contrast is the whole trick. Stillness before impact. Ordinary time before extremely non-ordinary time. Continuous maximum wump would erase the very contrast that makes a wump legible. A life at full volume is not a life of magnitude. It is a broken speaker.",
                "Measure a wump by completion, not by spectacle. A tiny wump performed fully will outrank a giant wump performed ironically. Irony is how people attend their own lives without having to be responsible for the ticket.",
            ],
            "maxim": "A tiny wump performed fully beats a giant wump performed ironically.",
            "exercise": "Name the last thing you called a good time. Did it compress, release, and recover? If one movement is missing, restore that one next, not a larger explosion.",
        },
        {
            "title": "On Micro-Wumps",
            "epigraph": "Maintenance is not a lesser art. It is the art that keeps the instrument in the room.",
            "body": [
                "The culture prefers the Great Wump: the wedding, the launch, the night that becomes a legend in the retelling. Legends are fine. They are also rare, expensive, and a poor diet. Between them, a person must still inhabit Thursday.",
                "A micro-wump is a complete cycle small enough to fit inside an ordinary day. It does not require an audience, a budget, or a new personality. It requires only that you stop treating the hour as packing material for some later real life.",
                "Examples, offered without shame: finishing a song instead of sampling fourteen. Cooking for one as if a guest were coming. Walking without a podcast until your thoughts have to do their own work. Sending the letter. Closing the laptop before the feed closes you.",
                "Do enough of these and the Great Wump, when it arrives, has a vessel to land in. Skip them and the Great Wump has to rebuild you from scratch, which it will not do kindly.",
            ],
            "maxim": "Never confuse volume with magnitude.",
            "exercise": "Perform one micro-wump today that you will not announce. Completeness is the point. Documentation is not.",
        },
        {
            "title": "The Interval",
            "epigraph": "The wump interval is a rhythm, not a deadline.",
            "body": [
                "People who have just discovered intensity try to schedule it like a gym. Tuesday: wump. Thursday: wump. Sunday: wump, larger. This produces a calendar that looks alive and a person who is not.",
                "An interval is the space in which a pulse remains a pulse. Too short, and you clip the waveform. Too long, and you forget what aliveness feels like. The correct length is not universal. It is local, bodily, and slightly embarrassing to admit, like hunger.",
                "A scheduled wump may still be sincere. Birthdays are scheduled. Harvests are scheduled. The bell was scheduled. Sincerity is not the enemy of the calendar. Compulsory peak-collection is.",
                "If the wump becomes compulsory, reduce pressure and restore play. Play is how the system remembers it is not a factory whistle.",
            ],
            "maxim": "If the wump becomes compulsory, reduce pressure and restore play.",
            "exercise": "Look at the next seven days. Circle one empty-looking hour. Protect it as recovery or as a micro-wump, not as a slot to be filled with errands.",
        },
        {
            "title": "Social Wumping",
            "epigraph": "Two people can wump in phase. This is called dancing, a good meeting, or love.",
            "body": [
                "A private wump can save a person. A shared wump can save a night. The danger is arriving at someone else’s peak with your own already in progress, or detonating in a kitchen because you have stored too much Tuesday.",
                "Conflict is often two waveforms refusing to make room. Properly timed wumps — a walk before the conversation, a breath before the reply, a feast after the labor — are not politeness in the weak sense. They are phase work.",
                "You cannot force resonance. You can become less armored. Armor is what you wear when you have confused safety with disappearance. A person who never wumps with others becomes very good at being right and very poor at being accompanied.",
                "The seminar on conflict exists because households are laboratories with snacks. Bring the snacks. Watch the timing.",
            ],
            "maxim": "A scheduled gathering may still be sincere.",
            "exercise": "In one conversation today, delay your reply by a single breath. Notice whether the other person becomes more themselves. That is a social wump so small it can hide in manners.",
        },
        {
            "title": "Recovery",
            "epigraph": "Rest is not anti-wump; rest is the loading screen.",
            "body": [
                "A culture that worships peaks will treat recovery as a character flaw. This is how people become proud of their exhaustion and then confused by their numbness. Recovery is not the opposite of the wump. It is the third movement. Without it, the first two were only impact.",
                "Plan recovery as part of the event, not as an apology afterward. If the recovery does not fit, the wump does not fit. This is not cowardice. This is conservation.",
                "Sleep, walking, silence, and the unfashionable act of doing nothing in particular are technologies. They convert heat into memory. A weekend that cannot be remembered on Wednesday was not a wump. It was noise with better lighting.",
                "The shark Wumphin, turning back into the current, is not a mascot for more. It is a figure for re-entering motion before stillness becomes disappearance — after rest, not instead of it.",
            ],
            "maxim": "Recovery converts impact into memory.",
            "exercise": "For the next predictable intensity — dinner, deadline, trip — write the recovery into the plan first. If you cannot find the space, reduce the event until you can.",
        },
        {
            "title": "The Wump Horizon",
            "epigraph": "There is no final wump. There is only the practice of returning.",
            "body": [
                "A life organized around a single Great Wump — the year everything changed, the night that explained you — will eventually starve. The horizon is not an event. It is a direction. You live toward the next sincere interval the way a swimmer lives toward air.",
                "Let a life contain a sequence of wumps W₁, W₂, … separated by intervals Δt₁, Δt₂, …. A viable wump life is not one in which W is maximized, but one in which no interval becomes so long that the person forgets what aliveness feels like.",
                "This is the mathematics of the Great Wump, such as it is: minimize oblivion, not boredom. Boredom is compression and can be used. Oblivion is a measurement outage. You cannot steer by a gauge that has gone dark.",
                "Keep humor and seriousness in the same pocket. Either one alone will make you impossible to live with, including for yourself.",
            ],
            "maxim": "A life without wumping is merely time passing — even if the graphs look busy.",
            "exercise": "Sketch your last fourteen days as peaks and rests only. Where is the longest flatline? That interval is your next experimental site. Do not fill it with spectacle. Fill it with a complete small cycle.",
        },
        {
            "title": "Living Toward the Next Wump",
            "epigraph": "The book ends where the next wump begins.",
            "body": [
                "Take a large one when the moment deserves it. Take a small one when the day is dull. Rest afterward. Then, like the shark Wumphin turning back into the current, re-enter motion before stillness becomes disappearance.",
                "You will not finish this practice. You will only return to it. Returning is the practice. The Institute exists because returning is easier in company, among people who take units of intensity seriously.",
                "The later volumes will tell you about the chamber, the equations, and the drum. They serve the same maintenance problem. If you read none of them, you may still wump. If you read all of them and never complete a cycle, you have only collected furniture.",
                "There is no final wump. There is only the practice of returning. Keep the pulse. Keep the interval. Keep Thursday from becoming packing material.",
            ],
            "maxim": "Keep wumping.",
            "exercise": "Before you close this book, perform the smallest possible complete wump available to you in the next ten minutes. Then recover. Then go on.",
        },
    ],
    glossary=[
        ("Wump (W)", "A completed pulse of lived intensity: compression, release, recovery."),
        ("Micro-wump", "A small cycle performed fully. Thursday’s technology."),
        ("Compression", "Gathered unused life. Also called boredom, hunger, or Tuesday."),
        ("Contrast", "How a wump remains legible. Without it, everything is noise."),
        ("Interval", "The space that keeps a pulse from becoming a factory whistle."),
        ("Recovery", "The third movement. Impact becomes memory, or it becomes debris."),
        ("Phase", "Whether your peak occupies the same present as someone else’s."),
        ("Wumphin", "A shark used as a figure of motion: re-enter the current after rest."),
        ("Oblivion", "A measurement outage. The gauge has gone dark."),
        ("The Great Wump", "A large completed cycle. Rare. A poor diet if eaten alone."),
    ],
    notes=[
        "This is the field manual. If you are new, start here and then attend The First Wump. If you are not new and have become theoretical, start here anyway. Theory is a fine instrument. It is a poor pulse.",
        "The 7% instruction is not a demand for spectacle. It is a correction for people who will not move until the movement is large enough to photograph. Increase spirit, not display.",
        "If this volume makes you want to found a competing institute, sit down. That is a false wump. Take a walk instead.",
        "Pair with Volume II when the problem is interior, Volume III when the problem is measurement, Volume IV when the problem is thinking you invented the drum.",
    ],
    closing=[
        "The Final Theorem. Let a life contain a sequence of wumps Wₙ separated by intervals Δtₙ. A viable wump life is not one in which W is maximized, but one in which no interval becomes so long that the person forgets what aliveness feels like.",
        "Take a large wump when the moment deserves it. Take a small one when the day is dull. Rest afterward. Re-enter motion before stillness becomes disappearance.",
        "The book ends where the next wump begins. There is no final wump. There is only the practice of returning.",
    ],
    final_line="Keep wumping.",
)


book(
    slug="the-unseen-wump",
    title="THE UNSEEN WUMP",
    running="THE UNSEEN WUMP",
    subtitle="A spiritual treatise on the soul’s rebound<br/>and the quiet practice of inner wumping",
    volume="Volume II of the Wump To Live Library",
    accent="#6e2c24",
    disclaimer=[
        "This book treats the inner life with the gravity reserved for liturgy, cartography, and the washing of very old glass. The chamber is a working term for the room in which a person metabolizes events into decisions. Inhabit it kindly.",
        "The practices here belong to attention, breath, and interval. They are offered as a manual for contact, not as a replacement for medical care or for any tradition you already keep.",
    ],
    preface_epigraph="What is silent is not empty. It is loading.",
    preface_attr="Anonymous wumper, overheard in a stairwell",
    preface=[
        "Most people first meet the wump as noise: a laugh that goes too far, a decision made at 11:47 p.m., a conversation that suddenly has weather in it. Those are public wumps. They leave evidence. They can be photographed, poorly.",
        "This book concerns the other kind. The unseen wump occurs in the inner chamber — that unadvertised room behind the face where a person negotiates with their own aliveness. It is the compression before a true sentence. It is the rebound after grief has sat down without asking. It is the small, unfashionable moment in which you become present enough to be changed by an ordinary Tuesday.",
        "Spiritual language is dangerous because it likes to become furniture. We will use it anyway, carefully, the way one uses a candle in a wooden house. The claim is modest: a life needs intervals of interior intensity. Without them, even a crowded week is a kind of disappearance.",
        "If you have come here hoping for a personality, we must disappoint you. The Institute does not require a guru. It requires a pulse. The rest is practice.",
    ],
    chapters=[
        {
            "title": "The Inner Chamber",
            "epigraph": "You cannot outsource a rebound.",
            "body": [
                "Every person maintains, whether they admit it or not, a private room in which events are metabolized. Some decorate this room with prayer. Some with planning. Some with a low, continuous apology. The chamber is not a mood. It is the place moods go to become decisions, or to fail to become them.",
                "The unseen wump begins when something in that room compresses: a truth too large for small talk, a joy too inconvenient for the meeting, a sorrow that will not file itself under ‘fine.’ Compression is not suffering. Compression is the gathering of force. The novice panics and opens every window. The practitioner stays long enough to feel the shape of the pressure.",
                "You will know the chamber by its acoustics. In ordinary life, language bounces. In the chamber, language arrives. A single honest sentence can occupy more space than an afternoon of performance. This is why people fear silence. Silence is not empty; it is the chamber with the door left unlatched.",
                "Do not confuse the chamber with isolation. Isolation is a locked room. The chamber is a listening room. Other people may never see it, but they will feel the weather that comes out of it. A person who never enters their own chamber becomes inexplicably loud in public, as if volume could substitute for depth.",
            ],
            "maxim": "If no one saw it, it can still have counted.",
            "exercise": "Sit for seven minutes without improving yourself. Name, privately, one pressure that has been waiting in the chamber. Do not solve it. Only admit that it has weight.",
        },
        {
            "title": "The Soul as an Elastic Vessel",
            "epigraph": "A brittle soul does not need more advice. It needs rebound.",
            "body": [
                "Let us speak of the soul the way a cooper speaks of a barrel: not as a cloud, but as a vessel expected to hold weather. An elastic soul expands under joy without bursting, and contracts under difficulty without cracking. A brittle soul does neither. It maintains a permanent expression of competence until it does not.",
                "Elasticity is trained. It is trained by small wumps performed fully: a walk taken for no reason, a letter written and actually sent, a cry that is not immediately translated into a task. Each complete cycle — compression, release, recovery — reminds the vessel that it can return to shape.",
                "People who live only at the surface imagine that spirituality is a kind of interior interior decorating. They collect calm the way others collect luggage tags. Calm is useful. Calm is not the point. The point is that the vessel can take a hit of meaning and still be a vessel afterward.",
                "If your inner life has become a museum of unfelt days, you do not need a more interesting personality. You need a wump that is sincere enough to move the air. Sincerity, in this usage, is not confession for an audience. It is contact.",
            ],
            "maxim": "The soul is not improved by irony. It is improved by contact.",
            "exercise": "Choose one ordinary act today — making coffee, locking a door, saying goodnight — and perform it as if it were a rite. Increase the spirit of it by exactly 7%. Do not announce this to anyone.",
        },
        {
            "title": "Breath as the Smallest Wumping",
            "epigraph": "Inhale is compression. Exhale is faith.",
            "body": [
                "Before there were drums, there were lungs. The breath is the most democratic wump on earth. It requires no equipment, no weekend, and no permission from a calendar that has already decided you are busy.",
                "Attend, for a moment, to the insulting simplicity of this. Air enters. The body becomes slightly more itself. Air leaves. The body trusts that more air exists. That trust, repeated without applause, is the entire spiritual curriculum in miniature.",
                "People complicate breathing because complication feels like effort, and effort feels like virtue. We will not complicate it. We will only notice that a neglected breath is a neglected pulse. When the day has become too Tuesday, the first restoration is not a philosophy. It is one complete cycle of air performed as if it mattered, because it does.",
                "There is a temptation to turn breath into a brand. Resist this. The unseen wump does not need a trademarked inhale. It needs you to stop abandoning your own body in order to become a more efficient ghost.",
            ],
            "maxim": "A breath taken fully beats a revelation performed ironically.",
            "exercise": "Before your next conversation, take three breaths that you do not use to prepare a personality. Enter speaking from the third.",
        },
        {
            "title": "The False Wump of Performance",
            "epigraph": "An audience can witness a wump. It cannot complete one for you.",
            "body": [
                "There exists a counterfeit intensity that looks, from a distance, like wumping. It is the story told too soon. It is the feeling announced before it has finished arriving. It is the retreat, the post, the sudden personality of someone who would like to be seen having an inner life without the inconvenience of having one.",
                "Performance is not evil. Theater is one of humanity’s great wumps. The error is using the stage as a substitute for the chamber. When every compression is immediately converted into content, nothing is allowed to ripen. The rebound happens in public and therefore does not happen at all.",
                "You will recognize the false wump by its hangover. A true inner wump leaves you quieter and more available. A performed wump leaves you hungry for confirmation. The first feeds the pulse. The second feeds the brand.",
                "This is delicate, because some lives are genuinely witnessed, and witnessing can be holy. The test is simple enough to be unfashionable: after the noise, are you more able to love the next ordinary hour? If not, you have not wumped. You have advertised.",
            ],
            "maxim": "Never confuse being witnessed with being changed.",
            "exercise": "Keep one good thing that happens this week entirely to yourself for twenty-four hours. Notice whether it becomes more real or less. That difference is data.",
        },
        {
            "title": "Prayer as Compression",
            "epigraph": "Ask, if you ask, as if the air is listening. Then do the dishes.",
            "body": [
                "Prayer, in the Institute’s sense, is directed compression. It is the act of gathering what you cannot carry and placing it somewhere that is not only your own nervous system. You may place it with God, with the dead, with the future, with a tree that has outlived several of your personalities. The destination matters less, at first, than the gathering.",
                "People who do not pray sometimes imagine that those who do are requesting favors from the weather. Some are. Others are simply refusing to hoard their own intensity. A wump trapped in the body becomes symptom. A wump offered becomes relation.",
                "We will not tell you whom to address. We will tell you that an unaddressed life begins to talk to itself in smaller and smaller rooms. Address is a spiritual technology. Even ‘I do not know who is there, but here is the weight’ is a complete sentence.",
                "After prayer, recover. The unseen wump is ruined by immediately checking whether it worked. Working, in this field, looks like being able to return to the day without abandoning it.",
            ],
            "maxim": "Recovery converts impact into memory, even when the impact was silent.",
            "exercise": "Write one sentence to whatever you suspect is larger than you. Fold it. Do not post it. Carry it until evening, then put it away as if it had been received.",
        },
        {
            "title": "The Dark Night of Unwumpedness",
            "epigraph": "Stagnation is not peace. Peace has a pulse.",
            "body": [
                "There comes a season when the inner chamber feels vacated. The old wumps no longer move the air. The jokes have a tax on them. Even beauty arrives like mail for a previous tenant. This is not a failure of character. It is a failure of interval.",
                "Unwumpedness is often misdiagnosed as maturity. The person becomes very good at logistics and very poor at inhabiting their own hours. Friends say they seem ‘fine,’ which is the most alarming of the polite words. Fine is what a pulse says when it has been asked to stop making trouble.",
                "The spiritual task here is not to manufacture a peak. Manufactured peaks are how people injure themselves in the name of aliveness. The task is to restore micro-wumps until the vessel remembers elasticity: a window opened, a song finished, a walk with no podcast, a meal cooked with theatrical seriousness for no guest.",
                "If the darkness is clinical, seek the kind of help that does not come from a manifesto. The Institute is serious about play and equally serious about not pretending that play replaces care. A wump is not a treatment. It is a practice for when treatment has made a little room.",
            ],
            "maxim": "If the wump becomes compulsory, reduce pressure and restore play.",
            "exercise": "Identify one thing this week that is merely happening and one thing that could be deliberately wumped. Do not choose the dramatic one. Choose the smaller one, and complete it.",
        },
        {
            "title": "Forgiveness as a Delayed Rebound",
            "epigraph": "Some wumps arrive years late, wearing ordinary clothes.",
            "body": [
                "Forgiveness is among the slowest wumps. It cannot be scheduled with the optimism of a calendar invitation. It is a rebound that waited in the chamber until the vessel was elastic enough not to shatter on the way out.",
                "People treat forgiveness as a moral exam. It is closer to physics. Something was compressed — harm, humiliation, a promise that did not keep its shape. The energy did not vanish. It sat. A delayed rebound is not weakness. It is the system refusing to explode on the original timetable.",
                "You are not required to call this holy. You are required, if you wish to remain inhabited, not to confuse rumination with remembrance. Rumination is compression without release. Remembrance is compression that has been allowed to become meaning.",
                "Sometimes the rebound is toward the other person. Sometimes it is toward your own future, which would like to stop living in a museum of the injury. Both can be unseen. Both count.",
            ],
            "maxim": "The next wump should answer the last one, not imitate it.",
            "exercise": "Name, privately, one old compression that has not yet rebounded. Do not force a conclusion. Ask only whether it wants movement or more time. Honor the answer for twenty-four hours.",
        },
        {
            "title": "The Communion of Simultaneous Wumps",
            "epigraph": "Two pulses in phase can move a room without raising their voices.",
            "body": [
                "The unseen wump is private, but it is not private property. Anyone who has sat beside a person in honest silence knows that interiors can touch without exhibition. Grief does this. So does laughter that arrives before language. So does a congregation that, for one hymn, remembers it is one animal with many lungs.",
                "We call this communion not to steal a church’s furniture but because no other word quite admits that separate chambers can share weather. You cannot force it. You can only become less armored, which is not the same as becoming less boundaried. Armor is what you wear when you have confused safety with disappearance.",
                "A spiritual life that never leaves the chamber becomes a hobby. A spiritual life that never enters the chamber becomes a crowd. The mature wumper learns the interval between solitude and company the way a musician learns bars of rest.",
                "If you are lonely, the answer may not be more people. It may be one person, or one place, with whom your unseen wump does not have to lie about its size.",
            ],
            "maxim": "A scheduled gathering may still be sincere.",
            "exercise": "This week, sit with one person without improving the silence. If you must speak, speak from the chamber, not from the résumé.",
        },
        {
            "title": "Ethics of the Quiet Rebound",
            "epigraph": "Your inner wump is yours. Its weather is not only yours.",
            "body": [
                "Because the unseen wump is invisible, people sometimes treat it as consequence-free. This is an error. A person who wumps internally by inventing enemies will export that weather. A person who wumps by becoming present will export a different weather. The chamber has a chimney.",
                "Spiritual practice without ethics is just mood management with better lighting. The Institute’s position is embarrassingly simple: an inner wump that requires someone else to become smaller is not a wump. It is a theft wearing incense.",
                "The opposite error is also common — refusing all intensity lest it disturb the room. That is not goodness. That is a life conducted at such low volume that even kindness cannot be heard. You are allowed to have a pulse in public, provided the pulse does not need a victim.",
                "Before a large inner release, ask a question so plain it feels beneath literature: will this make me more available to the living? If the answer is no, wait. Waiting is also a spiritual technology.",
            ],
            "maxim": "Never confuse volume with magnitude, especially in the soul.",
            "exercise": "After your next strong inner movement — anger, joy, sudden clarity — wait nine minutes before acting on it. See whether it remains itself. Magnitude stays. Theater often does not.",
        },
        {
            "title": "Living Toward the Unseen Horizon",
            "epigraph": "There is no final silence. There is only the next honest breath.",
            "body": [
                "A spiritual life organized around a single great wump — conversion, collapse, revelation, the weekend that finally explained you — will eventually starve. The horizon is not an event. It is a direction. You live toward the next sincere interval the way a swimmer lives toward air.",
                "This is the quietest possible ambition: not to become impressive, but to remain inhabitable. To keep the vessel elastic. To let small wumps keep the system from forgetting what contact feels like. To recover. To return.",
                "If there is a sacred image in this book, let it be unspectacular. A person in a kitchen. Evening. The day has been too much or not enough. They stand still long enough for the chamber to report the truth. Then they do the next kind thing, which may be rest.",
                "The unseen wump will not put your name on a building. It may, however, put you back inside your hours. That is the entire miracle, and it is enough.",
            ],
            "maxim": "Rest is not anti-wump; rest is the loading screen.",
            "exercise": "Before sleep, name one inner wump from the day, however small. Thank it as if it were a visitor who did not have to come. Then let the chamber go dark on purpose.",
        },
    ],
    glossary=[
        ("Inner chamber", "The unadvertised room in which events become decisions, or fail to."),
        ("Unseen wump", "A complete cycle of interior intensity that does not require an audience to exist."),
        ("Elasticity", "The soul’s capacity to take a hit of meaning and return to shape."),
        ("False wump", "Intensity converted into content before it has finished arriving."),
        ("Prayer", "Directed compression. Destination optional; gathering required."),
        ("Unwumpedness", "A long interval in which the chamber is still there and nobody is home."),
        ("Communion", "Separate chambers sharing weather without exhibition."),
        ("Delayed rebound", "A wump that waited until the vessel could survive it. Often called forgiveness."),
        ("Micro-wump", "A small cycle performed fully. The maintenance plan of the interior."),
        ("Horizon", "Not an event. A direction: the next sincere interval."),
    ],
    notes=[
        "Students often arrive hoping the spiritual volume will make them calmer. Calm may occur. It is a side effect, not a diploma. The work is contact: with pressure, with breath, with the next honest hour.",
        "If a chapter makes you want to announce a new personality, wait overnight. The chamber is allergic to rebrands. It prefers returns.",
        "Pair this volume with The First Wump if your inner life has become theoretical. Pair it with silence if your inner life has become a press conference.",
        "The Institute does not grade souls. If you must keep score, keep score of completions, not of peaks.",
    ],
    closing=[
        "Let U be the unseen intensity of a life, largely unphotographed. Let I be the sequence of interior intervals in which a person actually inhabits their own attention. A viable spiritual life is not one in which U is maximized, but one in which I never becomes so rare that the person forgets the chamber exists.",
        "You will not finish this practice. You will only return to it, which is the same thing the breath has been telling you since the first hour you were alive.",
        "Keep the chamber. Keep the pulse. Keep the seriousness of treating your own interior as a place worthy of care. Then go back to the dishes. The dishes, correctly understood, are also the path.",
    ],
    final_line="A life without inner wumping is merely time passing in a nicer room.",
)


book(
    slug="wump-mechanics",
    title="WUMP MECHANICS",
    running="WUMP MECHANICS",
    subtitle="Compression, release, and the<br/>thermodynamics of lived intensity",
    volume="Volume III of the Wump To Live Library",
    accent="#1e3a5f",
    disclaimer=[
        "The following treatise employs the language of physics, biology, and measurement. Equations herein describe operational quantities of intensity, completion, and recovery. They are field models for a life that can be maintained.",
        "The shark is used as a figure of necessary motion. A life that does not re-enter the current after rest begins to disappear. Cite the models wherever a laboratory of ordinary days requires a unit.",
    ],
    preface_epigraph="If you cannot measure it, you may still be having it.",
    preface_attr="Lab note, Institute for Applied Wumping",
    preface=[
        "Science, at its best, is a method for not lying to yourself in public. Wump mechanics is a method for not lying to yourself in private, using the instruments of science because a pulse deserves measurement.",
        "We begin with a unit. A wump, W, is a pulse of lived intensity: compression, release, and the recovery that makes the event rememberable. It is not identical with excitement, exercise, trauma, or a good party, though any of those may host one. The wump is the moment existence announces itself with unmistakable force and then, if you are lucky, lets you put the announcement down.",
        "Why borrow the sciences? Because the sciences already possess a mature vocabulary for interval, elasticity, friction, resonance, and heat. Ordinary self-help possesses a vocabulary for vibes. Vibes dissipate. Heat can be accounted for.",
        "The reader is asked to hold two thoughts at once: (1) none of this is laboratory fact, and (2) the body still behaves as if contrast, rest, and novelty were physical needs. The second thought is the one you can live inside.",
    ],
    chapters=[
        {
            "title": "On Units, Dimensions, and Honesty",
            "epigraph": "W has no SI unit. It has consequences anyway.",
            "body": [
                "Let us define our terms before they become poetry. Intensity, I, is the felt amplitude of an interval. Duration, Δt, is how long the interval remains distinguishable from the surrounding Tuesday. Recovery, R, is the subsequent period during which the system returns to a baseline capable of future amplitude. A wump is not I alone. A wump is the product of amplitude and completion.",
                "We may write W ≈ I × C, where C is a completion coefficient between 0 and 1. An enormous night with no recovery has a low C and therefore a disappointing W. A small walk fully inhabited may outscore it. This is not mysticism. This is accounting.",
                "Honesty is a measurement problem. People overreport peaks and underreport intervals. They remember the explosion and forget the fuse. Wump mechanics insists on the fuse. Without compression, release is only noise. Without recovery, release is only damage wearing a party hat.",
                "If you take nothing else from this chapter, take the discipline of naming. What you cannot name, you will either worship or ignore. Both errors produce poor data.",
            ],
            "maxim": "A tiny wump performed fully beats a giant wump performed ironically.",
            "exercise": "Log three intervals from the last forty-eight hours. Score each, privately, for intensity, completion, and recovery. Do not show anyone the scores. Science begins as a secret kept from one’s own vanity.",
        },
        {
            "title": "The Compression Phase",
            "epigraph": "Potential energy is just a wump refusing to start on time.",
            "body": [
                "Compression is the gathering of unused life. Boredom is compression. Anticipation is compression. The suspicion that your calendar has replaced your pulse is compression. In mechanical terms, you are loading a spring. In human terms, you are becoming tired of your own impersonation of a person.",
                "Novices treat compression as a defect to be anesthetized. They add inputs: screens, snacks, opinions. This is like holding a spring down with more furniture. The stored force does not vanish. It changes the furniture.",
                "Useful compression has a direction. It wants a release that answers it. Hunger wants food, not a speech about food. Loneliness wants contact, not a theory of contact. The mature wumper asks, ‘What is this pressure for?’ rather than ‘How do I make this pressure stop existing?’",
                "There is a limit. Springs yield. People yield. If compression has become panic, you are no longer in the poetic chapter. You are in the chapter where you reduce load and seek actual help. Mechanics includes knowing when the model no longer applies.",
            ],
            "maxim": "Wumping begins with pressure. Do not be ashamed of the gathering.",
            "exercise": "Locate one current compression. Write a single sentence stating what release it might be asking for. If you cannot tell, the experiment is to wait, not to detonate.",
        },
        {
            "title": "Elasticity and the Modulus of a Tuesday",
            "epigraph": "Stiffness is not strength. Strength returns to shape.",
            "body": [
                "In materials science, the elastic modulus describes how a substance responds to stress and then, if one is fortunate, un-responds. Human Tuesdays have a modulus. Some people deform under a difficult hour and remain deformed. Others take the hour, store it, and come back to shape in time for dinner.",
                "Elasticity is trained by cycles, not by slogans. Each completed micro-wump is a repetition: load, release, recover. The walk for no reason. The joke pursued past dignity. The project begun at 11:47 p.m. and then, crucially, slept on. These are not productivity hacks. They are tensile tests you can survive.",
                "A life of constant maximum intensity has a terrible modulus. Continuous peak load erases contrast, and contrast is how a wump remains legible to the nervous system. If everything is a wump, nothing is. This is the thermodynamics of boredom wearing a leather jacket.",
                "Measure your Tuesday. If it cannot bend, it will break. If it bends and never returns, you do not have a personality. You have a dent.",
            ],
            "maxim": "The wump interval is a rhythm, not a deadline.",
            "exercise": "Increase one ordinary activity by 7% in spirit — not in duration, not in spend, not in audience. Record whether you returned to shape afterward. That return is the datum.",
        },
        {
            "title": "Conservation of Intensity (Frequently Violated)",
            "epigraph": "Energy is conserved. Attention is not.",
            "body": [
                "Physics is famous for conservation laws. Wump mechanics is famous for violating them. You may leave a conversation with more life than you brought, which is not how closed systems behave. You may also leave a weekend with less, despite adding experiences as if they were mass.",
                "The resolution is that a person is not a closed system. We exchange intensity with rooms, with music, with other nervous systems, with weather. The error is imagining that more input always increases W. Often it increases noise, which is intensity that cannot complete.",
                "Let N be noise and S be signal. A useful day maximizes the ratio S/N, not the raw count of events. This is why a single true conversation can outweigh a festival. The festival may have higher I and a catastrophic C.",
                "If you are exhausted after ‘doing everything,’ you did not fail at living. You ran an experiment with poor isolation. Next time, reduce variables. Science is often subtraction.",
            ],
            "maxim": "Never confuse volume with magnitude.",
            "exercise": "Remove one input from tomorrow — an extra tab, an extra opinion, an extra obligation you are using as anesthesia. Observe whether intensity falls or becomes more measurable.",
        },
        {
            "title": "Waveforms, Resonance, and Phase",
            "epigraph": "Two people can wump in phase. This is called dancing, or a good meeting, or love.",
            "body": [
                "A wump, plotted over time, is a waveform: a rise, a peak, a fall, a rest. People who fear rest clip the waveform and wonder why their lives sound like a broken speaker. Rest is not the absence of the signal. Rest is part of the signal.",
                "Resonance occurs when an external rhythm matches a system’s natural frequency. This is why the right song can reorganize a kitchen. It is why the wrong job can make even weekends feel like a mis-tuned instrument. You are not ‘too sensitive.’ You are a physical object in a vibrating world.",
                "Phase matters. Arrive too early to someone else’s wump and you become friction. Arrive too late and you become audience to a fire already out. Properly timed wumps — including the social kind — are an applied science of phase. Conflict, as the seminars will argue, is often two waveforms refusing to make room for each other’s peaks.",
                "You cannot force resonance. You can clear a little space, reduce damping, and notice when the room begins to behave like one instrument.",
            ],
            "maxim": "A scheduled wump may still be sincere if the phase is honest.",
            "exercise": "In one conversation today, delay your reply by a single breath so you are not merely overlapping. Notice whether the other person becomes more themselves. That is phase work.",
        },
        {
            "title": "Friction, Drag, and Social Resistance",
            "epigraph": "Some environments are viscous. Swim accordingly.",
            "body": [
                "Not all resistance is neurosis. Some of it is drag. Families, offices, and group chats have viscosity. They slow sudden movement, sometimes protectively, sometimes because they have mistaken stillness for virtue. A wump moving through high drag spends energy on the medium rather than the motion.",
                "The scientific response is not always more force. More force in a viscous medium produces heat and little displacement. The response may be a different medium: a walk, a closed door, a friend who does not require you to be smaller. Or it may be a slower waveform that the medium can actually transmit.",
                "There is also useful friction. Completely frictionless lives produce people who cannot stop. Brakes are a technology. So are manners. The Institute does not recommend becoming a particle in vacuum. It recommends knowing what you are spending force against.",
                "If every wump of yours creates the same argument, you do not have a unique personality. You have a repeating collision. Change the angle of approach before you change your entire identity.",
            ],
            "maxim": "The next wump should answer the last one, not imitate it.",
            "exercise": "Identify one source of drag in your week. Decide whether to reduce speed, change medium, or apply a smaller, cleaner force. Do not do all three at once. That is not an experiment; that is a tantrum with a clipboard.",
        },
        {
            "title": "Thermodynamics: You Cannot Wump Forever",
            "epigraph": "Entropy does not care about your weekend.",
            "body": [
                "The first law, restated for our purposes: you cannot create intensity from nowhere, but you can convert it. Food, sleep, novelty, and contact are convertible. Shame is a very expensive conversion.",
                "The second law, restated: every wump costs order somewhere. A magnificent night may disorder the morning. A magnificent morning may require an earlier night. Systems that deny this become moralizing. They call fatigue a character flaw so they do not have to budget for heat.",
                "Continuous maximum wump would erase the contrast that makes a wump legible. It would also, in any real body, produce waste heat until the instrument fails. This is not a metaphor borrowed from engines. This is why you have already lived a version of it and called it burnout, which is a word that sounds like a lifestyle and behaves like physics.",
                "Plan recovery as part of the event, not as an apology afterward. Recovery is not anti-wump. Recovery is how impact becomes memory instead of debris.",
            ],
            "maxim": "Recovery converts impact into memory.",
            "exercise": "For the next wump you can predict — a dinner, a deadline, a trip — write the recovery into the plan first. If the recovery does not fit, the wump does not fit. This is conservation, not cowardice.",
        },
        {
            "title": "Observers, Error, and the Measurement Problem",
            "epigraph": "The act of announcing a wump often changes the wump.",
            "body": [
                "In certain physical theories, observation is not innocent. In human lives, it is even less innocent. Tell a room you are about to have a breakthrough and you may only have a performance. Keep the breakthrough until it completes and you may have data.",
                "Measurement error in this field is mostly narrative. We plot our lives as highlight reels, then feel confused when the unplotted hours feel unreal. The unplotted hours are the majority of the dataset. Any model that ignores them will look inspiring and fail on Wednesday.",
                "There is a useful humility here. You will not get a perfect reading of your own intensity. You will get better at noticing completion. Completion is easier to observe than essence. Did the thing finish? Did you return? Can you still be kind in the next hour? These are instruments you already own.",
                "Beware of people, including inner people, who want to be the official meter of your life. A pulse does not need a spokesperson. It needs interval.",
            ],
            "maxim": "If the wump becomes compulsory, reduce pressure and restore play.",
            "exercise": "Describe one recent wump in twenty words, then in two. If the two-word version is more honest, keep it. Precision is often subtraction.",
        },
        {
            "title": "Chaos, Improvisation, and Sensitive Dependence",
            "epigraph": "A 7% change in spirit is not small if it is applied at the right point.",
            "body": [
                "Some systems are linear: more input, more output. People are only linear when they are pretending. In actual rooms, a joke, a delay, a window opened at the right minute can reorganize the whole evening. This is sensitive dependence, which is the dignified name for ‘how did that help?’",
                "Improvised wumps scare planners because they cannot be budgeted. They should scare planners a little. They should not be banned. A life with no improvisation is a closed-form equation that has forgotten it is being lived by an animal.",
                "The Institute’s 7% instruction is a chaos-aware tool. You do not need a new life. You need a perturbation. Increase the spirit of one existing motion. If the system is near a threshold, the small change will not look small from the inside of next month.",
                "Document perturbations the way a lab documents anomalies: briefly, without mythology. Mythology is how a useful accident becomes a prison of identity.",
            ],
            "maxim": "Rest is not anti-wump; rest is the loading screen.",
            "exercise": "Apply a 7% spiritual increase to something already on your calendar. Do not add a new event. The experiment is perturbation, not expansion.",
        },
        {
            "title": "Field Equations of Aliveness",
            "epigraph": "The model is wrong. The pulse is not.",
            "body": [
                "We may now assemble a field equation and then refuse to worship it. Let a life contain wumps W₁, W₂, … separated by intervals Δt₁, Δt₂, …. Let L, aliveness, be a function not of the maximum W but of whether any Δt becomes so long that the organism forgets the sensation of being inhabited.",
                "In other words: minimize oblivion, not boredom. Boredom is compression and can be used. Oblivion is a measurement outage. You cannot steer by a gauge that has gone dark.",
                "The mature wumper therefore stops asking how to maximize W and asks what rhythm of intensity and recovery makes a life feel occupied from the inside. This is the difference between collecting peaks and developing a pulse. Peaks are souvenirs. A pulse is an instrument still in use.",
                "If this sounds less exciting than a manifesto, good. Manifestos are high-I, low-C. A pulse can be taken to work.",
            ],
            "maxim": "A life without wumping is merely time passing — even if the graphs look busy.",
            "exercise": "Sketch your last fourteen days as a crude waveform, peaks and rests only. Where is the longest flatline? That interval is your next experimental site. Do not fill it with spectacle. Fill it with a complete small cycle.",
        },
    ],
    glossary=[
        ("Wump (W)", "A completed pulse of lived intensity: compression, release, recovery."),
        ("Intensity (I)", "Felt amplitude. Necessary, insufficient."),
        ("Completion (C)", "A coefficient from 0 to 1. Did the cycle finish, or only advertise?"),
        ("Recovery (R)", "The interval that turns impact into memory instead of debris."),
        ("Compression", "Gathered unused life. Also called boredom, hunger, or Tuesday."),
        ("Modulus", "How a Tuesday bends and whether it returns to shape."),
        ("Noise (N)", "Intensity that cannot complete. Often sold as a lifestyle."),
        ("Phase", "Whether your peak occupies the same present as someone else’s."),
        ("Drag", "Environmental viscosity. Not always your personality."),
        ("Oblivion", "A measurement outage. The gauge has gone dark."),
    ],
    notes=[
        "Do not memorize the field equations at the expense of sleep. If you find yourself optimizing W while the body fails, you have failed the lab in a very modern way.",
        "Bring a notebook to the scientific seminar. Do not bring a personality that needs to win physics. There is nothing to win. There is only better data about your own interval.",
        "When the model and the body disagree, believe the body, then update the model. This is the entire method.",
        "If a partner, child, or coworker becomes the subject of your ‘experiments’ without consent, you are not doing science. You are doing a monologue with clipboards.",
    ],
    closing=[
        "The Final Model, such as it is: let Wₙ be a sequence of wumps and Δtₙ the rests between them. A viable wump life is not one in which W is maximized, but one in which no interval becomes so long that the person forgets what aliveness feels like.",
        "Take a large wump when the moment deserves it. Take a small one when the day is dull. Rest afterward. Re-enter motion before stillness becomes disappearance. This is maintenance.",
        "Keep your instruments humble. Keep your recoveries on the calendar. Keep humor and seriousness in the same pocket, because either one alone will make you impossible to live with, including for yourself.",
    ],
    final_line="The equations describe the pulse. The pulse was the result.",
)


book(
    slug="the-annals-of-wumping",
    title="THE ANNALS OF WUMPING",
    running="THE ANNALS OF WUMPING",
    subtitle="From the first drum to the present pulse:<br/>a history of humanity’s oldest undocumented practice",
    volume="Volume IV of the Wump To Live Library",
    accent="#6b3a12",
    disclaimer=[
        "This history is offered as a chronicle of intervals. Dates are given where the record allows. Sources include drums, bells, festival calendars, labor songs, and the stubborn human habit of making an ordinary night matter more than it had to.",
        "Where this book meets archaeology, musicology, or labor history, it reads those fields as a colleague. The Great Wump is the subject. The record is the method.",
    ],
    preface_epigraph="The record is incomplete. The pulse is not.",
    preface_attr="Marginal note in a borrowed chronicle",
    preface=[
        "History, as usually taught, prefers wars, inventions, and men who sat for portraits. Wumping left fewer portraits. It left drums with worn heads, festival calendars, factory whistles, dance floors, and the mysterious human habit of making an ordinary night matter more than it had to.",
        "This volume argues that the wump is among humanity’s oldest practices: the deliberate intensification of an interval so that a life may remember it was lived. People have always needed contrast. They have always needed recovery. They have always, sooner or later, hit something until it rang.",
        "We will not pretend that every feast was holy or every riot a sacrament. Some wumps were cruel. The Institute does not baptize them. We study the pulse, including its failures, because a species that cannot tell a festival from a catastrophe will keep producing both and calling the result ‘the times.’",
        "Read this as a chronicle of intervals. Empires rise. The drum continues. That is the plot.",
    ],
    chapters=[
        {
            "title": "The First Drum (Date Disputed)",
            "epigraph": "Before writing, there was repetition with feeling.",
            "body": [
                "Someone, somewhere, hit something hollow and heard the world answer. Scholars of the Institute place this event at the beginning of shared time. The precise century is less important than the discovery: sound could be organized into a pulse, and a pulse could organize people.",
                "The first drum was not entertainment as we use the word. It was a technology for making many nervous systems occupy the same present. Hunting parties, night watches, grief, and weather all become more survivable when they have a shared interval. A solo wump can save a person. A communal wump can save a night.",
                "We should resist the romance that prehistoric life was an endless peak. It was mostly walking, waiting, and trying not to die. That is exactly why the drum mattered. Contrast is precious when the baseline is survival. The wump was not extra. It was how the extra got into the day.",
                "If there is an origin myth here, let it be small: a hand, a hollow, a second hand joining. History begins not with a king but with phase.",
            ],
            "maxim": "A tiny wump performed fully beats a giant wump performed ironically — even in the Pleistocene, probably.",
            "exercise": "Make a pulse with what you have: a table, a knee, a mug. Keep it for one minute. Notice whether your thoughts agree to occupy the same minute. That agreement is ancient.",
        },
        {
            "title": "Agricultural Intervals and the Invention of the Calendar",
            "epigraph": "Once you can store grain, you can schedule a wump. This is both gift and trap.",
            "body": [
                "Agriculture did not invent intensity. It invented surplus, waiting, and the year as a repeating machine. Planting and harvest are among the oldest large-scale wumps: compression through labor, release through bringing in, recovery through whatever feast the stores allowed.",
                "The calendar is a wump technology. It says: not now, then. It protects planting from perpetual festival and festival from being forgotten. It also, eventually, becomes a tyrant that cannot hear a pulse that arrives off-schedule. Every later bureaucracy is a calendar that has grown a building.",
                "Harvest wumps could be generous. They could also be extraction wearing a wreath. History is not a children’s pageant. The same interval that bound a village could bind someone to a field that was not theirs. When we praise rhythm, we must ask whose year it was.",
                "Still, the agricultural lesson remains: a culture that cannot mark completion will live in undifferentiated labor. Undifferentiated labor is a long flatline with better tools.",
            ],
            "maxim": "The wump interval is a rhythm, not a deadline — though harvest disagrees in a loud voice.",
            "exercise": "Mark one completion this week with a small, deliberate feast. It may be toast. Toast, historically, has launched worse religions.",
        },
        {
            "title": "Classical Misreadings: Oracles, Arenas, and the Public Pulse",
            "epigraph": "The ancients wumped in public and called it politics, sport, or fate.",
            "body": [
                "In the city-states that later Europeans decided were the beginning of seriousness, wumping took civic form. Processions, theater, games, and oracles were machines for moving a crowd through compression and release. A tragedy is a guided wump. So is a race. So, less admirably, is a spectacle that requires someone else’s suffering to complete the waveform.",
                "The oracle is interesting because it formalized uncertainty as a ritual. People arrived compressed with questions and left with language. Sometimes the language was useful. Sometimes it was theater with better lighting. The Institute recognizes both as historical facts.",
                "What the classical world understood, and later office culture forgot, is that a public needs shared peaks or it will invent unsavory ones. If there is no play, there will be a rumor. If there is no feast, there will be a faction. The pulse will out.",
                "We inherit their architecture and their errors. Columns are easy to copy. Wisdom about rest is harder. Many a modern person lives like a minor senator: always in forum, never in recovery.",
            ],
            "maxim": "Never confuse volume with magnitude. Arenas are loud; not all of them are large.",
            "exercise": "Attend, once this week, something with a beginning, middle, and end that is not a screen. A match, a play, a service, a reading. Practice being in a public waveform without having to run it.",
        },
        {
            "title": "Medieval Bells, Fasts, and Festival Excess",
            "epigraph": "The bell did not tell you what to feel. It told you when.",
            "body": [
                "Medieval time was not empty; it was rung. Bells divided the day into intervals you could hear from a field. This is among the great forgotten kindnesses of history: a pulse bigger than one person’s resolve. You did not have to remember to return. The air remembered for you.",
                "Fast and feast are a paired technology. Compression, then release. The error of later centuries was keeping only one half — either endless restriction or endless availability — and then wondering why the soul felt like bad engineering. A feast with no fast becomes noise. A fast with no feast becomes a personality disorder with a holiday.",
                "Carnival, where it existed, was a scheduled overflow. It was not anarchy so much as a pressure valve with costumes. People who fear carnival often fear what their own compression would do if it ever found a legal door. The historical record suggests the door is safer than the explosion.",
                "None of this requires nostalgia for plague, hierarchy, or the wrong end of a sword. It requires noticing that interval was once a public utility.",
            ],
            "maxim": "A scheduled wump may still be sincere. The bell believed this for centuries.",
            "exercise": "Choose a daily bell — an actual alarm, a church, a kettle. When it rings, stop for thirty seconds and return to your body. You are borrowing a medieval infrastructure. Thank it internally. It cannot hear you, which is historically accurate.",
        },
        {
            "title": "The Age of Reason Attempts to Ban the Wump",
            "epigraph": "They did not ban it. They renamed it ‘enthusiasm’ and disapproved.",
            "body": [
                "Enlightenment, in its better moods, gave us measurement, rights, and the courage to distrust a story simply because a man in a wig had told it. In its worse moods, it treated intensity as a rural embarrassment. The pulse was suspected of being unhygienic.",
                "This produced a curious historical creature: the person who can explain everything and inhabit nothing. Coffeehouses hummed. Salons glittered. Meanwhile the body, unconsulted, continued to need contrast. When official culture under-wumps, unofficial culture over-wumps. See: every era’s panic about dancing.",
                "Reason is not the enemy of the wump. Reason is how you keep a wump from becoming a mob. The enemy is a reason that has forgotten it lives in an animal. An animal will eventually chew through the lecture.",
                "The Institute honors this period by insisting on method. We are, in that sense, children of the Enlightenment: we want a claim that can be lived. We are also children of the drum: we want you to inhabit a Tuesday long enough to feel it.",
            ],
            "maxim": "If the wump becomes compulsory, reduce pressure and restore play — a sentence several revolutions needed and did not use.",
            "exercise": "Read one page of something dense, then immediately do one thing with your hands. History suggests the mind works better when it is not the only organ invited to the century.",
        },
        {
            "title": "Industrial Compression and the Factory Whistle",
            "epigraph": "The whistle was a bell that had gotten a job.",
            "body": [
                "Industry gathered human hours with unprecedented success. It also flattened them. The factory whistle is a perfect historical object: a communal pulse in service of production rather than inhabitation. Everyone heard the same interval. Not everyone owned the interval.",
                "This is when recovery became suspicious. Rest looked like theft from the machine. Play looked like a leak. The weekend had to be invented, fought for, and then, in later decades, quietly filled with other kinds of work until it resembled a smaller factory with better lighting.",
                "Labor songs, dances after shifts, and the stubborn persistence of jokes at the machine are not decorations on the record. They are evidence that people will install micro-wumps inside hostile waveforms in order not to disappear. History’s unofficial thesis: the pulse tries to live.",
                "If your present job feels like a whistle you did not consent to, you are not being poetic. You are being accurate. The question, as always, is whether you can restore interval without pretending the whistle is a hymn.",
            ],
            "maxim": "Recovery converts impact into memory. Denied recovery converts impact into injury, then into ‘just how it is.’",
            "exercise": "Protect one off-whistle interval this week as if it were a historical right, because it is. No errands inside it. Errands are how the factory colonizes the kitchen.",
        },
        {
            "title": "Jazz, Radio, and the Democratization of Rebound",
            "epigraph": "A rhythm section is a parliament that actually listens.",
            "body": [
                "The twentieth century put pulse in the air. Radio meant a stranger’s wump could enter a kitchen. Recordings meant a dead musician could still reorganize a living room. This was not only culture. It was a change in the available waveforms of ordinary life.",
                "Jazz, among other musics, taught a public lesson the academy keeps needing: swing is scheduled surprise. The time is firm so the playing can be free. People who cannot keep time cannot improvise; they can only collide. The seminar on rhythm is, in this sense, a historical reenactment with better chairs.",
                "Of course the market learned to sell intensity by the unit. A pulse that can be packaged will be packaged. The old problem returns in new clothes: volume mistaken for magnitude, peaks collected like stamps, recovery skipped because silence does not photograph well.",
                "Still, something generous happened. More kinds of people could find a waveform that fit their nervous system. History is not only a sequence of thefts. Sometimes it is a widening of the drum circle, even if someone tries to charge admission.",
            ],
            "maxim": "The next wump should answer the last one, not imitate it. Cover bands, be warned.",
            "exercise": "Play one piece of music as if it were a public utility, not background. Stand up. If you feel foolish, good; foolishness is often the body re-entering history.",
        },
        {
            "title": "The Late Century: Self-Help Discovers the Village",
            "epigraph": "They sold back to us what harvest already knew.",
            "body": [
                "By the late twentieth century, people with excellent lighting began to notice that other people felt unreal. They wrote books. Some of the books were good. Many rediscovered interval and named it as if they had built it in a garage. The village, had it been consulted, might have mentioned harvest, bells, and sitting together without a brand.",
                "This is not a sneer at needing help. Modern life really did thin out the old public pulses and then charge rent on the replacements. A seminar, a retreat, even a slightly absurd institute can be a prosthetic village. Prostheses are allowed. Pretending they are ancient without the debts of history is not.",
                "The useful inheritance of self-help is permission: you may treat your own pulse as a subject of study. The dangerous inheritance is the belief that optimization is the same as inhabitation. A fully optimized person may still be absent. The annals are full of absent people with excellent systems.",
                "The Wump Institute stands in this late tradition and knows it. A seminar, a retreat, a library: these are how a public pulse is rebuilt when the old furniture of gathering is gone.",
            ],
            "maxim": "A life without wumping is merely time passing — a sentence every century rewrites and then forgets.",
            "exercise": "Borrow one ‘village’ practice this week: eat with someone without a device, or mark a completion out loud. You are not being retro. You are being statistically normal for most of human time.",
        },
        {
            "title": "The Great Unwumping of the Early Screens",
            "epigraph": "Infinite scroll is a festival with no closing hymn.",
            "body": [
                "Then came a machine that could offer a little rebound at any hour, which is another way of saying it could prevent compression from ever completing. The feed is not evil. It is a waveform with no rest, which in wump mechanics is a contradiction and in business is a feature.",
                "Historically, even carnival ended. Dawn arrived, sticky and unimpressed. The screen does not have to arrive at dawn. It can extend Tuesday until Tuesday has no edges. People began to report a new symptom: having seen everything and been in nothing.",
                "The Institute’s position is not Luddite. Tools that carry other people’s pulses can be a mercy — the song, the letter, the far-away face. The danger is substituting stimulation for interval. Stimulation is I without C. It spikes. It does not harvest.",
                "Every age thinks its distraction is unprecedented. Ours happens to be portable. The correction is old: restore contrast. Let some hours be unimproved. Let some wumps finish. Put the machine down as if it were a festival that has, at last, reached its hymn.",
            ],
            "maxim": "Rest is not anti-wump; rest is the loading screen. The pun is intentional and, unfortunately, accurate.",
            "exercise": "Close one infinite interval tonight. Choose a last thing. Let it be last. History will not record this, which is why it will work.",
        },
        {
            "title": "Toward a Present Pulse",
            "epigraph": "We are not the first to need a drum. We may be the first to need permission to hear one.",
            "body": [
                "The present is not a peak in the story. It is another interval. People still gather, still joke past reason, still cook with theatrical seriousness, still begin things at 11:47 p.m. The practice did not die. It lost its public furniture and now has to be rebuilt in kitchens, seminars, walks, and books that can be used.",
                "If there is a task for the living, it is to reinstall interval without reinstalling cruelty. To have feast without requiring a victim. To have rhythm without a whistle that owns you. To have inner wumps that do not become performances, and public wumps that do not become mobs.",
                "The Institute offers seminars not because it invented the pulse but because the pulse, in this century, is lonely. Lonely pulses get strange. They either vanish or explode. Instruction is a way of saying: you are not the first, you will not be the last, here is how people have kept the drum from becoming a weapon.",
                "History does not end. It recovers, if we let it. Then it wumps again, smaller or larger, and someone writes it down as if it were new.",
            ],
            "maxim": "There is no final wump. There is only the practice of returning — the oldest plot we have.",
            "exercise": "Tell one true story of a wump from your own life to one other person, without improving it into a legend. You have now entered the annals. They are mostly oral. They always were.",
        },
    ],
    glossary=[
        ("Drum", "The first known technology for making many nervous systems occupy one present."),
        ("Calendar", "A machine for saying not now, then. Gift and trap."),
        ("Bell", "Public interval. A pulse larger than one person’s resolve."),
        ("Fast / feast", "Paired compression and release. Either half alone becomes bad engineering."),
        ("Whistle", "A bell that got a job. Communal pulse in service of production."),
        ("Carnival", "Scheduled overflow. Safer than the explosion, historically."),
        ("Swing", "Scheduled surprise. Firm time so the playing can be free."),
        ("Prosthetic village", "A seminar, retreat, or institute used when the old furniture of gathering is gone."),
        ("Feed", "A festival with no closing hymn. High I, low C."),
        ("Annals", "Mostly oral. You enter them by telling a true story without improving it."),
    ],
    notes=[
        "History students of the Institute are asked not to become unbearable at dinner. You may mention bells. You may not lecture your relatives about their factory-whistle souls unless they have asked.",
        "The point of the chronicle is permission. You are allowed to want interval. You are not the first. You will not be the last. The drum does not require your originality, only your hands.",
        "If this volume makes you nostalgic for a past that would not have included you, put it down and take a walk in the century you actually have. Nostalgia is a wump that refuses to rebound into the present.",
        "Bring the annals to the conflict seminar. Many fights are two calendars refusing to share a Tuesday.",
    ],
    closing=[
        "The chronicle’s last theorem is the same as the first book’s, because history is not a different species of time. Let a people contain a sequence of wumps separated by intervals. A viable culture is not one in which spectacle is maximized, but one in which no interval becomes so long that the living forget what aliveness feels like.",
        "You have now been issued four volumes in service of a maintenance problem. Use them. Walk. Ring something. Recover. Return.",
        "The drum is still there. It was never in the museum. It was in the hands.",
    ],
    final_line="Keep wumping. The record will catch up, or it won’t. The pulse does not require a footnote.",
)
